In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\indur\OneDrive\Desktop\power bi projects\Public_Transport_Delay\ETL\-Smart-Traffic-Accident-Risk-Prediction-System-Using-Machine-Learning\DATA\cleaned_smart_accident.csv')
df

,Unnamed: 0,WEATHER_CONDITION,VISIBILITY,TRAFFIC_DENSITY,VEHICLE_SPEED,ROAD_CONDITION,HOUR,SPEED_LIMIT,ROAD_TYPE,PRECIPITATION,JUNCTION,TRAFFIC_SIGNAL,ACCIDENT_OCCURRENCE
0,0,Clearsky,4.5,Lowtraffic,31,Muddy,6,40,Serviceroad,Snowfall,0,1,0
1,1,Sunny,7.0,Meddensity,74,Icy,7,70,Expressway,Heavyrain,0,1,1
2,2,Storm,10.0,Light,110,Dryroad,12,50,Rural,Heavyrain,0,0,0
3,3,Clearsky,3.0,Meddensity,108,Waterwater,1,80,Expressway,Snowfall,1,0,0
4,4,Misty,13.8,Hgh,115,Muddy,7,60,Urbanroad,Snowfall,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,59995,Misty,10.0,High,10,Waterwater,12,50,Bridgelane,Fogdrizzle,0,0,0
59996,59996,Rainy,10.0,Medtraffic,100,Dryroad,23,50,Highway,Norain,1,0,0
59997,59997,Snow,9.1,Jampacked,59,Roughroad,12,70,City,Lightrain,1,0,1
59998,59998,Foggy,4.8,Low,49,Dryroad,3,100,Serviceroad,Lightrain,0,0,1
59999,59999,Storm,11.6,Traffichigh,64,Icy,12,40,Serviceroad,Heavyrain,1,1,0

In [3]:
#feature engineering

# 1.group by 

risk = df.groupby(['WEATHER_CONDITION','TRAFFIC_DENSITY','PRECIPITATION'])['ACCIDENT_OCCURRENCE'].mean().reset_index()
risk.rename(
    columns = {
        'ACCIDENT_OCCURRENCE':'RISK_SCORE'
    },
    inplace=True
)

df = df.merge(risk,on= ['WEATHER_CONDITION','TRAFFIC_DENSITY','PRECIPITATION'],).round(2)

df

,Unnamed: 0,WEATHER_CONDITION,VISIBILITY,TRAFFIC_DENSITY,VEHICLE_SPEED,ROAD_CONDITION,HOUR,SPEED_LIMIT,ROAD_TYPE,PRECIPITATION,JUNCTION,TRAFFIC_SIGNAL,ACCIDENT_OCCURRENCE,RISK_SCORE
0,0,Clearsky,4.5,Lowtraffic,31,Muddy,6,40,Serviceroad,Snowfall,0,1,0,0.55
1,1,Sunny,7.0,Meddensity,74,Icy,7,70,Expressway,Heavyrain,0,1,1,0.46
2,2,Storm,10.0,Light,110,Dryroad,12,50,Rural,Heavyrain,0,0,0,0.51
3,3,Clearsky,3.0,Meddensity,108,Waterwater,1,80,Expressway,Snowfall,1,0,0,0.48
4,4,Misty,13.8,Hgh,115,Muddy,7,60,Urbanroad,Snowfall,0,0,0,0.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,59995,Misty,10.0,High,10,Waterwater,12,50,Bridgelane,Fogdrizzle,0,0,0,0.42
59996,59996,Rainy,10.0,Medtraffic,100,Dryroad,23,50,Highway,Norain,1,0,0,0.46
59997,59997,Snow,9.1,Jampacked,59,Roughroad,12,70,City,Lightrain,1,0,1,0.50
59998,59998,Foggy,4.8,Low,49,Dryroad,3,100,Serviceroad,Lightrain,0,0,1,0.44
59999,59999,Storm,11.6,Traffichigh,64,Icy,12,40,Serviceroad,Heavyrain,1,1,0,0.53

In [4]:
#RADIO

df['SPEED_RISK'] = (df['SPEED_LIMIT'] / df['VEHICLE_SPEED']).round(2)
df

,Unnamed: 0,WEATHER_CONDITION,VISIBILITY,TRAFFIC_DENSITY,VEHICLE_SPEED,ROAD_CONDITION,HOUR,SPEED_LIMIT,ROAD_TYPE,PRECIPITATION,JUNCTION,TRAFFIC_SIGNAL,ACCIDENT_OCCURRENCE,RISK_SCORE,SPEED_RISK
0,0,Clearsky,4.5,Lowtraffic,31,Muddy,6,40,Serviceroad,Snowfall,0,1,0,0.55,1.29
1,1,Sunny,7.0,Meddensity,74,Icy,7,70,Expressway,Heavyrain,0,1,1,0.46,0.95
2,2,Storm,10.0,Light,110,Dryroad,12,50,Rural,Heavyrain,0,0,0,0.51,0.45
3,3,Clearsky,3.0,Meddensity,108,Waterwater,1,80,Expressway,Snowfall,1,0,0,0.48,0.74
4,4,Misty,13.8,Hgh,115,Muddy,7,60,Urbanroad,Snowfall,0,0,0,0.48,0.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,59995,Misty,10.0,High,10,Waterwater,12,50,Bridgelane,Fogdrizzle,0,0,0,0.42,5.00
59996,59996,Rainy,10.0,Medtraffic,100,Dryroad,23,50,Highway,Norain,1,0,0,0.46,0.50
59997,59997,Snow,9.1,Jampacked,59,Roughroad,12,70,City,Lightrain,1,0,1,0.50,1.19
59998,59998,Foggy,4.8,Low,49,Dryroad,3,100,Serviceroad,Lightrain,0,0,1,0.44,2.04
59999,59999,Storm,11.6,Traffichigh,64,Icy,12,40,Serviceroad,Heavyrain,1,1,0,0.53,0.62

In [5]:
df['LOW_VISIBILITY'] = (df['VISIBILITY'] < 3).astype(int)

In [6]:
df['IS_NIGHT'] =(df['HOUR'] >= 20) | (df['HOUR'] <= 5).astype(int)
df['IS_NIGHT'] = df['IS_NIGHT'].astype(int)

In [7]:
HIGH_TRAFFIC =[

    'High',
    'Medtraffic',
    'Jampacked',
    'Low'
    'Meddensity'
    'Lowtraffic	'

]

df['HIGH_TRAFFIC'] = df['TRAFFIC_DENSITY'].isin(HIGH_TRAFFIC).astype(int)

In [8]:
df['HOUR'] =df['HOUR'].astype(str).str[:2]
df['HOUR'] =df['HOUR'].astype(int)

In [9]:
df.replace([np.inf,-np.inf],np.nan,inplace=True)

df.fillna(df.median(numeric_only=True),inplace=True)

In [12]:
df.to_csv('feature_engineering.csv')
df.to_excel('Smart_traffic_accident_prediction_using_ML.xlsx')